name: Daily Auto Shorts

on:
  schedule:
    - cron: '30 6 * * *' # Roz subah 6:30 UTC (India Time: 12:00 PM Dopehar)
  workflow_dispatch: # Button manual run ke liye

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write # History save karne ki permission
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Tools
        run: |
          sudo apt-get install ffmpeg
          pip install -r requirements.txt

      - name: Run Bot Script
        run: python main.py

      - name: Save History
        if: success()
        run: |
          git config --global user.name "AutoBot"
          git config --global user.email "bot@github.com"
          git add posted_history.txt
          git commit -m "New video posted" || echo "No changes"
          git push
